[package]
name = "debugchrome"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
rayon = "1.10.0"
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde_json = "1.0.140"
tungstenite = "0.26.2"
url = "2.5.4"
